services:
  frontend:
    container_name: frontend-dev-bb
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    container_name: api-dev-bb
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+asyncpg://bookbuddy:bookbuddy@postgres:5432/bookbuddy
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    build:
      context: ./database
    container_name: db-dev-bb
    restart: always
    environment:
      POSTGRES_USER: bookbuddy
      POSTGRES_PASSWORD: bookbuddy
      POSTGRES_DB: bookbuddy
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
